export const BUSINESS_TYPES = [
  { value: "ecommerce", label: "Ecommerce" },
  { value: "lavado_autos", label: "Lavado de autos" },
  { value: "renta_mesas", label: "Renta mesas / carpas" },
  { value: "restaurante", label: "Restaurante" },
  { value: "cafeteria", label: "Cafetería" },
  { value: "tienda", label: "Tienda" },
  { value: "deposito_cerveza", label: "Expendio de cerveza" },
  { value: "materiales", label: "Materiales de construcción" },
  { value: "taqueria", label: "Taquería" },
  { value: "peluqueria", label: "Peluquería" },
  { value: "taller_mecanico", label: "Taller mecánico" },
  { value: "consultorio", label: "Consultorio" },
  { value: "gimnasio", label: "Gimnasio" },
  { value: "escuela", label: "Escuela" },
  { value: "spa", label: "Spa" },
  { value: "ferreteria", label: "Ferretería" },
  { value: "farmacia", label: "Farmacia" },
  { value: "panaderia", label: "Panadería" },
  { value: "veterinaria", label: "Veterinaria" },
  { value: "imprenta", label: "Imprenta" },
  { value: "boutique", label: "Boutique" },
  { value: "mascotas", label: "Tienda de mascotas" },
  { value: "tenis", label: "Tienda de tenis" },
  { value: "otro", label: "Otro" },
] as const;
